const wilayas = [
    { code: "01", nomFR: "Adrar", nomAR: "أدرار" },
    { code: "02", nomFR: "Chlef", nomAR: "الشلف" },
    { code: "03", nomFR: "Laghouat", nomAR: "الأغواط" },
    { code: "04", nomFR: "Oum El Bouaghi", nomAR: "أم البواقي" },
    { code: "05", nomFR: "Batna", nomAR: "باتنة" },
    { code: "06", nomFR: "Béjaïa", nomAR: "بجاية" },
    { code: "07", nomFR: "Biskra", nomAR: "بسكرة" },
    { code: "08", nomFR: "Béchar", nomAR: "بشار" },
    { code: "09", nomFR: "Blida", nomAR: "البليدة" },
    { code: "10", nomFR: "Bouira", nomAR: "البويرة" },
    { code: "11", nomFR: "Tamanrasset", nomAR: "تمنراست" },
    { code: "12", nomFR: "Tébessa", nomAR: "تبسة" },
    { code: "13", nomFR: "Tlemcen", nomAR: "تلمسان" },
    { code: "14", nomFR: "Tiaret", nomAR: "تيارت" },
    { code: "15", nomFR: "Tizi Ouzou", nomAR: "تيزي وزو" },
    { code: "16", nomFR: "Alger", nomAR: "الجزائر" },
    { code: "17", nomFR: "Djelfa", nomAR: "الجلفة" },
    { code: "18", nomFR: "Jijel", nomAR: "جيجل" },
    { code: "19", nomFR: "Sétif", nomAR: "سطيف" },
    { code: "20", nomFR: "Saïda", nomAR: "سعيدة" },
    { code: "21", nomFR: "Skikda", nomAR: "سكيكدة" },
    { code: "22", nomFR: "Sidi Bel Abbès", nomAR: "سيدي بلعباس" },
    { code: "23", nomFR: "Annaba", nomAR: "عنابة" },
    { code: "24", nomFR: "Guelma", nomAR: "قالمة" },
    { code: "25", nomFR: "Constantine", nomAR: "قسنطينة" },
    { code: "26", nomFR: "Médéa", nomAR: "المدية" },
    { code: "27", nomFR: "Mostaganem", nomAR: "مستغانم" },
    { code: "28", nomFR: "M'Sila", nomAR: "المسيلة" },
    { code: "29", nomFR: "Mascara", nomAR: "معسكر" },
    { code: "30", nomFR: "Ouargla", nomAR: "ورقلة" },
    { code: "31", nomFR: "Oran", nomAR: "وهران" },
    { code: "32", nomFR: "El Bayadh", nomAR: "البيض" },
    { code: "33", nomFR: "Illizi", nomAR: "إليزي" },
    { code: "34", nomFR: "Bordj Bou Arréridj", nomAR: "برج بوعريريج" },
    { code: "35", nomFR: "Boumerdès", nomAR: "بومرداس" },
    { code: "36", nomFR: "El Tarf", nomAR: "الطارف" },
    { code: "37", nomFR: "Tindouf", nomAR: "تندوف" },
    { code: "38", nomFR: "Tissemsilt", nomAR: "تسمسيلت" },
    { code: "39", nomFR: "El Oued", nomAR: "الوادي" },
    { code: "40", nomFR: "Khenchela", nomAR: "خنشلة" },
    { code: "41", nomFR: "Souk Ahras", nomAR: "سوق أهراس" },
    { code: "42", nomFR: "Tipaza", nomAR: "تيبازة" },
    { code: "43", nomFR: "Mila", nomAR: "ميلة" },
    { code: "44", nomFR: "Aïn Defla", nomAR: "عين الدفلى" },
    { code: "45", nomFR: "Naâma", nomAR: "النعامة" },
    { code: "46", nomFR: "Aïn Témouchent", nomAR: "عين تموشنت" },
    { code: "47", nomFR: "Ghardaïa", nomAR: "الغرداية" },
    { code: "48", nomFR: "Relizane", nomAR: "غليزان" },
];
let wilaya=document.getElementById("wilaya");
for(let i=0; i<wilayas.length;i++){
    let option=document.createElement("option")
    option.value=wilayas[i].nomFR;
    option.text=wilayas[i].nomAR;
    wilaya.append(option)
}
